# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

schedules:
- cron: "0 0 * * *"
  displayName: Daily Midnight Build
  branches:
   include:
     - master
     - Feature/*
- cron: "0 12 * * 0"
  displayName: Weekly Sunday Noon Build
  branches:
   include:
     - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'DevOpsDeploy'
    appType: 'webApp'
    WebAppName: 'gw-secrets-core-webapp'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'

- task: owaspzap@1
  displayName: 'OWASP ZAP'
  inputs:
    aggressivemode: true
    threshold: '75'
    scantype: 'targetedScan'
    url: 'https://gw-secrets-core-webapp.azurewebsites.net/'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/owaspzap'
    ArtifactName: 'Zap Reports'
